### PR TITLE
Add Error Prone Bug detector

### PR DESCRIPTION
**Pull request by vorburger**
~~NO LONGER blocked by https://github.com/google/error-prone/issues/3909~~

This adds https://errorprone.info

### CODE REVIEW

**Comment by vorburger** [comment]
@mosesn do you have any interest in reviewing this? Just to double check with an extra pair of eyes to make sure that this won't break anything. It shouldn't obviously, these are "clean-up" changes. I do also totally understand if you don't really have the time, in which case I'll just merge this as-is (which should be fine).

**Comment by vorburger** [comment]
@mosesn OK this is the "final" rebased version... now I won't change this, anymore.

I'll merge this in ~48h if I don't hear back.

**Comment by vorburger** [comment]
> I'll merge this in ~48h if I don't hear back.

Nah I'll just go ahead and merge this now, because I had to rebase it for 3rd time now.

It's just easier to collaborate on future changes with this merged.

**Comment by mosesn** [comment]
@vorburger Sorry I missed your tag before but I'm a strong +1 on this patch.  It does seem to prevent a few classes from being compiled though, like MultiCauseOutputException.  Perhaps you need to try cleaning locally to make sure that everything builds?

**Comment by vorburger** [comment]
@mosesn erm, how do you mean, "prevent a few classes from being compiled"? The `MultiCauseIOException` was adapted to pass EP, in this PR. This builds for me locally, and passed the PR build on CI ... or did I miss something? If the current latest `master` branch is failing to build for you, do you want to open a new issue about it, with a build failure log? (But that would be strange.)

**Comment by mosesn** [comment]
@vorburger done! #127

**Pull request merged**
